### ISSUE TITLE
Portability of compilation (of the compiler program)

### ISSUE THREAD

**Issue by ElykDeer** [SaplingStudios/EMA#3]
Details described here:
https://stackoverflow.com/questions/44360640/

**Comment by ElykDeer** [comment]
@DavidDev21 We have a couple options to fix this issue... We can add the Boost library to the project, though I don't want to learn Boost for this.  We could make this code only be able to be compiled on Linux, or we could forcefully update the compilers on our Bash-For-Windows to let us compile with a newer version of g++.  Finally, we could create a different work around than using the filesystem library of c++17.

**Comment by ElykDeer** [comment]
@DavidDev21 If you're okay with it, we can update our gcc instillation on the Bash For Windows subsystem so it will allow us to use the new features... The guide to updating is here, but I'd need your confirmation on whether you want to do that, for the c++17 features.  https://solarianprogrammer.com/2017/05/04/building-gcc-wsl-windows-subsystem-linux/

**Comment by DavidDev21** [comment]
updating the gcc installation sounds like easier solution.

**Comment by ElykDeer** [comment]
Cool, then we will be using gcc-7.1 on the Linux Subsystem For Windows by followoing [these](https://solarianprogrammer.com/2017/05/04/building-gcc-wsl-windows-subsystem-linux/) steps, which will allow us to compiler the compiler, which then does not need C++17 features.  This means that when compiling on Linux proper, the make file command will have to be updated as stated in the README.md
